[package]
name = "discovery-crate"
description = "Crate type detection for sw-checklist"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
discovery-cargo.workspace = true
toml.workspace = true
