[package]
name = "wasm-html"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
checklist-result.workspace = true
walkdir.workspace = true
