[package]
name = "cli-output"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
checklist-config.workspace = true
checklist-result.workspace = true
